version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8089:8080"
    environment:
      - APP_ENV=local
    networks:
      - laravel
    depends_on:
      - mysql
    extra_hosts:
      - "id.eideasy.eu:172.18.0.1"
  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "laravel"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravel"
      MYSQL_DATABASE: "laravel"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3906:3306"
    volumes:
      - 'mysql8:/var/lib/mysql'
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
volumes:
  mysql8:
    driver: local
